In [30]:
import pandas as pd
import numpy as np
import os

In [39]:
a = None
b = 'test'

In [37]:
if not a:
    print('test')

test

In [41]:
if b:
    print('test')

test

In [4]:
urls = pd.read_csv('/mnt/storage/labs/mitchell/projects/matchup-workflow-data/publish-dev-data/temp/05-download-urls.csv', names=['granid','granurl','wlon','slat','elon','nlat'])

In [6]:
num_urls = len(urls)

In [9]:
unique_sats = np.unique([gid[0:-13] for gid in urls['granid']])

In [10]:
unique_sats

array(['A', 'T', 'V1J', 'VS'], dtype='<U3')

In [13]:
satdir_files = os.listdir('/mnt/storage/labs/mitchell/projects/matchup-workflow-data/publish-dev-data/temp/satellite-files')

In [14]:
satdir_files

['aqua', 'terra', 'snpp', 'jpss1', 'jpss2']

In [28]:
l2_files = []
for root, dirs, files in os.walk('/mnt/storage/labs/mitchell/projects/matchup-workflow-data/publish-dev-data/temp/satellite-files/'):
    for file in files:
        if file.endswith('.L2'):
            l2_files.append(file)

In [29]:
l2_files

['A2002233174000.L2',
 'A2004286150500.L2',
 'A2005178035500.L2',
 'A2005178132500.L2',
 'A2005201165000.L2',
 'A2008355185000.L2',
 'A2008355171500.L2',
 'A2008356175500.L2',
 'A2010141175500.L2',
 'A2010290145500.L2',
 'A2010299162000.L2',
 'A2010302151000.L2',
 'A2010305154000.L2',
 'A2011033163000.L2',
 'A2011176010000.L2',
 'A2011283155000.L2',
 'A2018189183000.L2',
 'A2018189165000.L2',
 'A2020027122000.L2',
 'A2020049114500.L2',
 'A2021031003500.L2',
 'A2021030225500.L2',
 'T2002233160000.L2',
 'T2005178114500.L2',
 'T2005201151000.L2',
 'T2010141161000.L2',
 'T2010290131000.L2',
 'T2010290113500.L2',
 'T2010299131000.L2',
 'T2010305124000.L2',
 'T2011033105000.L2',
 'T2011033122500.L2',
 'T2011283124000.L2',
 'T2018189151500.L2',
 'T2020049073500.L2',
 'T2021030185000.L2',
 'VS2018189163001.L2',
 'VS2018189181200.L2',
 'VS2020027115401.L2',
 'VS2020049114201.L2',
 'VS2021030231800.L2',
 'VS2021031010000.L2',
 'V1J2018189171801.L2',
 'V1J2020027124200.L2',
 'V1J2020027110600.L2',
 'V1J2020049123001.L2',
 'V1J2020049104800.L2',
 'V1J2021031001200.L2',
 'V1J2021030223000.L2']

In [ ]:
import os
for root, dirs, files in os.walk('/mnt/storage/labs/mitchell/projects/matchup-workflow-data/publish-dev-data/temp/satellite-files'):
    for file in files:
        if file.endswith(".txt"):
             print(os.path.join(root, file))

In [38]:
#df = pd.read_csv('/mnt/storage/labs/mitchell/projects/pic-algorithm/2022-analysis/srp-workflow/02b-matchup-dataframe-configuration/04-matchup-df-formatted.csv')
field = pd.read_csv('/mnt/storage/labs/mitchell/projects/pic-algorithm/2022-analysis/srp-workflow/01-field-data-configuration/05-field-data.csv')

/home/spinkham/sunnysenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (2,3,10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [41]:
ids = ['tn376_171699','amt21_45542','tn376_175572','s981013w_104813','amt20_37999',
       's020821w_116768','s100521e_143914','s050720e_127018','s020821w_116701','amt20_39341',
       'rr2004_182934','copas08_59451','amt15_3809','en616_166812','tan1109_189527',
       'amt20_36189','mv1101_78988','amt16_12663','amt20_38684','copas08_59179']
pic_sample = field.loc[field.ID.isin(ids)]

In [42]:
pic_sample.to_csv('/mnt/storage/labs/mitchell/projects/matchup-workflow-data/publish-dev-data/temp/01-pic-sample-field.csv', index=False)

In [43]:
string='a25_viirs'

In [47]:
'viirs' not in string

False

In [13]:
fp = '/mnt/storage/labs/mitchell/projects/matchup-workflow-data/publish-dev-data/temp/amt-l1a-bounding-box-expansion-test-file.csv'

In [14]:
df_l1a = pd.read_csv(fp, names=['station','granid','granurl','wlon','slat','elon','nlat'])

In [35]:
curr_df = df_l1a.loc[df_l1a['station']=='amt16_6688']

In [41]:
curr_df.loc[curr_df['granid'].str[0]=='A']

,station,granid,granurl,wlon,slat,elon,nlat
0,amt16_6688,A2005147135000,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-6.1586,-29.856083,-4.1586,-27.856083
1,amt16_6688,A2005147134500,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-6.1586,-29.856083,-4.1586,-27.856083
2,amt16_6688,A2005147135001,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-6.1586,-29.856083,-4.1586,-27.856083

In [6]:
urls = []
wlons = []
elons = []
slats = []
nlats = []

for url in df_l1a['granurl'].unique():
    curr_df = df_l1a.loc[df_l1a['granurl']==url]
    urls.append(url)
    wlons.append(curr_df['wlon'].min())
    elons.append(curr_df['elon'].max())
    slats.append(curr_df['slat'].min())
    nlats.append(curr_df['nlat'].max())

#download_l1as = pd.DataFrame(data=[urls,wlons,slats,elons,nlats], columns=['granurl','wlon','slat','elon','nlat'])
#download_l1as.to_csv(dict_args['ofile'][0], index=False, header=False)

In [8]:
data=[urls,wlons,slats,elons,nlats]

In [11]:
pd.DataFrame({'granurl':urls,'wlon':wlons,'slat':slats,'elon':elons,'nlat':nlats})

,granurl,wlon,slat,elon,nlat
0,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-8.445250,-29.856083,-4.158600,-27.419250
1,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-8.419383,-29.856083,-4.158600,-27.423850
2,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-8.445250,-29.856083,-4.158600,-27.419250
3,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-8.775933,-29.660717,-5.165417,-27.360050
4,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-13.034300,-28.980583,-8.708800,-26.531867
5,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-13.034300,-28.980583,-8.708800,-26.531867
6,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-16.743833,-28.213333,-12.499467,-25.820067
7,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-16.743833,-28.213333,-12.499467,-25.820067
8,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-21.011933,-27.425133,-16.733767,-24.980817
9,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-21.011933,-27.425133,-16.733767,-24.980817
10,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-25.136033,-26.491583,-21.506117,-23.169250
11,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-26.005100,-23.833600,-23.979117,-20.870717
12,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-26.005100,-23.833600,-23.979117,-20.870717
13,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-26.005100,-23.709450,-23.979117,-20.870717
14,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-7.793517,-29.856083,-4.158600,-27.539083
15,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-12.152150,-29.070100,-8.239417,-26.706350
16,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-15.814800,-28.229200,-12.443300,-25.997117
17,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-15.843083,-28.229200,-12.443300,-25.992500
18,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-20.452633,-27.528783,-16.259517,-25.089683
19,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-24.012733,-26.623850,-20.820967,-24.394167
20,https://oceandata.sci.gsfc.nasa.gov/cmr/getfil...,-23.991183,-26.603300,-20.954633,-24.398850

In [7]:
pd.DataFrame(data=[urls,wlons,slats,elons,nlats], columns=['granurl','wlon','slat','elon','nlat'])

ValueError: 5 columns passed, passed data had 21 columns

In [2]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePathOrBuffer',
    sep=<no_default>,
    delimiter=None,
    header='infer',
    names=<no_default>,
    index_col=None,
    usecols=None,
    squeeze=False,
    prefix=<no_default>,
    mangle_dupe_cols=True,
    dtype: 'DtypeArg | None' = None,
    engine=None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=False,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression='infer',
    thousands=None,
    decimal: 'str' = '.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    escapechar=None,
    comment=None,
    encoding=None,
    encoding_errors: 'str | None' = 'strict',
    dialect=None,
    error_bad_lines=None,
    warn_bad_lines=None,
    on_bad_lines=None,
    delim_whitespace=False,
    low_memory=True,
    memory_map=False,
    float_precision=None,
    storage_options: 'StorageOptions' = None,
)
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Delimiter to use. If sep is None, the C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator by Python's builtin sniffer
    tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
    different from ``'\s+'`` will be interpreted as regular expressions and
    will also force the use of the Python parsing engine. Note that regex
    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, default ``None``
    Alias for sep.
header : int, list of int, default 'infer'
    Row number(s) to use as the column names, and the start of the
    data.  Default behavior is to infer the column names: if no names
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a multi-index on the columns
    e.g. [0,1,3]. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : array-like, optional
    List of column names to use. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : int, str, sequence of int / str, or False, default ``None``
  Column(s) to use as the row labels of the ``DataFrame``, either given as
  string name or column index. If a sequence of int / str is given, a
  MultiIndex is used.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g. when you have a malformed file with delimiters at
  the end of each line.
usecols : list-like or callable, optional
    Return a subset of the columns. If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in `names` or
    inferred from the document header row(s). For example, a valid list-like
    `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a DataFrame from ``data`` with element order preserved use
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
    in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to True. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
squeeze : bool, default False
    If the parsed data only contains one column then return a Series.
prefix : str, optional
    Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
mangle_dupe_cols : bool, default True
    Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
    'X'...'X'. Passing in False will cause data to be overwritten if there
    are duplicate names in the columns.
dtype : Type name or dict of column -> type, optional
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
    'c': 'Int64'}
    Use `str` or `object` together with suitable `na_values` settings
    to preserve and not interpret dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.
engine : {'c', 'python'}, optional
    Parser engine to use. The C engine is faster while the python engine is
    currently more feature-complete.
converters : dict, optional
    Dict of functions for converting values in certain columns. Keys can either
    be integers or column labels.
true_values : list, optional
    Values to consider as True.
false_values : list, optional
    Values to consider as False.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : list-like, int or callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (int)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning True if the row should be skipped and False otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with engine='c').
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : scalar, str, list-like, or dict, optional
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values.  By default the following values are interpreted as
    NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
    'nan', 'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether `na_values` is passed in, the behavior is as follows:

    * If `keep_default_na` is True, and `na_values` are specified, `na_values`
      is appended to the default NaN values used for parsing.
    * If `keep_default_na` is True, and `na_values` are not specified, only
      the default NaN values are used for parsing.
    * If `keep_default_na` is False, and `na_values` are specified, only
      the NaN values specified `na_values` are used for parsing.
    * If `keep_default_na` is False, and `na_values` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the `keep_default_na` and
    `na_values` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing na_filter=False can improve the performance
    of reading a large file.
verbose : bool, default False
    Indicate number of NA values placed in non-numeric columns.
skip_blank_lines : bool, default True
    If True, skip over blank lines rather than interpreting as NaN values.
parse_dates : bool or list of int or names or list of lists or dict, default False
    The behavior is as follows:

    * boolean. If True -> try parsing the index.
    * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
      result 'foo'

    If a column or index cannot be represented as an array of datetimes,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an object data type. For
    non-standard datetime parsing, use ``pd.to_datetime`` after
    ``pd.read_csv``. To parse an index or column with a mixture of timezones,
    specify ``date_parser`` to be a partially-applied
    :func:`pandas.to_datetime` with ``utc=True``. See
    :ref:`io.csv.mixed_timezones` for more.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If True and `parse_dates` is enabled, pandas will attempt to infer the
    format of the datetime strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.
keep_date_col : bool, default False
    If True and `parse_dates` specifies combining multiple columns then
    keep the original columns.
date_parser : function, optional
    Function to use for converting a sequence of string columns to an array of
    datetime instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. Pandas will try to call `date_parser` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by `parse_dates` into a single array
    and pass that; and 3) call `date_parser` once for each row using one or
    more strings (corresponding to the columns defined by `parse_dates`) as
    arguments.
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If True, use a cache of unique, converted dates to apply the datetime
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

    .. versionadded:: 0.25.0
iterator : bool, default False
    Return TextFileReader object for iteration or getting chunks with
    ``get_chunk()``.

    .. versionchanged:: 1.2

       ``TextFileReader`` is a context manager.
chunksize : int, optional
    Return TextFileReader object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

    .. versionchanged:: 1.2

       ``TextFileReader`` is a context manager.
compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and
    `filepath_or_buffer` is path-like, then detect compression from the
    following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
    decompression). If using 'zip', the ZIP file must contain only one data
    file to be read in. Set to None for no decompression.
thousands : str, optional
    Thousands separator.
decimal : str, default '.'
    Character to recognize as decimal point (e.g. use ',' for European data).
lineterminator : str (length 1), optional
    Character to break file into lines. Only valid with C parser.
quotechar : str (length 1), optional
    The character used to denote the start and end of a quoted item. Quoted
    items can include the delimiter and it will be ignored.
quoting : int or csv.QUOTE_* instance, default 0
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
    QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
doublequote : bool, default ``True``
   When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive quotechar elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    One-character string used to escape other characters.
comment : str, optional
    Indicates remainder of line should not be parsed. If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter `header` but not by
    `skiprows`. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
    treated as the header.
encoding : str, optional
    Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    .. versionchanged:: 1.2

       When ``encoding`` is ``None``, ``errors="replace"`` is passed to
       ``open()``. Otherwise, ``errors="strict"`` is passed to ``open()``.
       This behavior was previously only the case for ``engine="python"``.

    .. versionchanged:: 1.3.0

       ``encoding_errors`` is a new argument. ``encoding`` has no longer an
       influence on how encoding errors are handled.

encoding_errors : str, optional, default "strict"
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: `delimiter`, `doublequote`, `escapechar`,
    `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
    override values, a ParserWarning will be issued. See csv.Dialect
    documentation for more details.
error_bad_lines : bool, default ``None``
    Lines with too many fields (e.g. a csv line with too many commas) will by
    default cause an exception to be raised, and no DataFrame will be returned.
    If False, then these "bad lines" will be dropped from the DataFrame that is
    returned.

    .. deprecated:: 1.3.0
       The ``on_bad_lines`` parameter should be used instead to specify behavior upon
       encountering a bad line instead.
warn_bad_lines : bool, default ``None``
    If error_bad_lines is False, and warn_bad_lines is True, a warning for each
    "bad line" will be output.

    .. deprecated:: 1.3.0
       The ``on_bad_lines`` parameter should be used instead to specify behavior upon
       encountering a bad line instead.
on_bad_lines : {'error', 'warn', 'skip'}, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

        - 'error', raise an Exception when a bad line is encountered.
        - 'warn', raise a warning when a bad line is encountered and skip that line.
        - 'skip', skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
    used as the sep. Equivalent to setting ``sep='\s+'``. If this option
    is set to True, nothing should be passed in for the ``delimiter``
    parameter.
low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set False, or specify the type with the `dtype` parameter.
    Note that the entire file is read into a single DataFrame regardless,
    use the `chunksize` or `iterator` parameter to return the data in chunks.
    (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for `filepath_or_buffer`, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : str, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are ``None`` or 'high' for the ordinary converter,
    'legacy' for the original lower precision pandas converter, and
    'round_trip' for the round-trip converter.

    .. versionchanged:: 1.2

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib`` as header options. For other URLs (e.g.
    starting with "s3://", and "gcs://") the key-value pairs are forwarded to
    ``fsspec``. Please see ``fsspec`` and ``urllib`` for more details.

    .. versionadded:: 1.2

Returns
-------
DataFrame or TextParser
    A comma-separated values (csv) file is returned as two-dimensional
    data structure with labeled axes.

See Also
--------
DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_fwf : Read a table of fixed-width formatted lines into DataFrame.

Examples
--------
>>> pd.read_csv('data.csv')  # doctest: +SKIP
File:      ~/sunnysenv/lib/python3.9/site-packages/pandas/io/parsers/readers.py
Type:      function

In [5]:
field = pd.read_csv('/mnt/storage/labs/mitchell/projects/matchup-workflow-data/publish-dev-data/01-field-data.csv')

In [4]:
field.head()

,MatchupID,CruiseName,StationTime,yyyy-mm-ddThh:mm:ss,Longitude,Latitude,StationDataID,StationInfoID,Depth,Shallowest,...,cgp715,cg412,cg440,cg488,cg510,cg550,cg630,cg650,cg676,cg715
0,0,s980917w,NaN,1998-09-17 13:46:48,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,s980917w,NaN,1998-09-17 13:47:13,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,s980917w,NaN,1998-09-17 13:47:35,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,s980917w,NaN,1998-09-17 13:47:56,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,s980917w,NaN,1998-09-17 13:48:18,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
)
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order.

    .. versionchanged:: 0.25.0
       If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3
File:           ~/sunnysenv/lib/python3.9/site-packages/pandas/core/frame.py
Type:           type
Subclasses:     SubclassedDataFrame

In [8]:
field.UWid[field.UWid.isnull()==True]

2756    NaN
4065    NaN
4066    NaN
4067    NaN
4068    NaN
4069    NaN
4070    NaN
4071    NaN
4072    NaN
4073    NaN
4227    NaN
7092    NaN
18732   NaN
26827   NaN
28623   NaN
40045   NaN
40046   NaN
40061   NaN
40114   NaN
40272   NaN
40372   NaN
42444   NaN
42581   NaN
43239   NaN
44806   NaN
50706   NaN
51687   NaN
51688   NaN
51850   NaN
51935   NaN
51936   NaN
52249   NaN
52250   NaN
53495   NaN
56897   NaN
56898   NaN
56899   NaN
56900   NaN
56905   NaN
56955   NaN
56971   NaN
Name: UWid, dtype: float64

In [4]:
abs(a)>180

False